variables:
  TEST_IMAGE: nexus:8123/giz/web:$CI_PIPELINE_ID
before_script:
  - docker login nexus:8123 -u admin -p *197Ost35
build:
 stage: build
 script:
  - docker build -t $TEST_IMAGE .
  - docker push $TEST_IMAGE
deploy:
 stage: deploy
 script:
  - kubectl config use-context kubernetes-admin@kubernetes
  - kubectl rolling-update web --image $TEST_IMAGE --update-period=1s --poll-interval=100ms -n giz
